name: build and push alpine-awscli image

on:
  push:
    tags:
      - "alpine-awscli/v*"

jobs:
  build_docker_image:
    uses: ./.github/workflows/reuse-workflow.yml
    with:
      container_name: alpine-awscli
    # secrets dont have to be passed as the reusable workflow can ask it from the repository (it's the same repository as the caller)
    # secrets:
    #   dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
    #   dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}