name: build and push debian-awscli image

on:
  push:
    tags:
      - "debian-awscli/v*"

jobs:
  build_docker_image:
    uses: ./.github/workflows/reuse-workflow.yml
    with:
      container_name: debian-awscli
    secrets: inherit