name: build and push alpine-awscli image

on:
  push:
    tags:
      - "alpine-awscli/v*"

jobs:
  build_docker_image:
    uses: ./.github/workflows/reuse-workflow.yml
    with:
      container_name: alpine-awscli
    secrets: inherit