name: build and push debian-awscli image

on:
  push:
    branches:
      - "main"
    paths: 
      - containers/debian-awscli/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: containers/debian-awscli
          file: containers/debian-awscli/Dockerfile
          push: true
          tags: | 
            ${{ secrets.DOCKERHUB_USERNAME }}/debian-awscli:1.0.0
            ${{ secrets.DOCKERHUB_USERNAME }}/debian-awscli:latest
          cache-from: type=registry,ref=containers/debian-awscli:latest
          cache-to: type=inline