name: build and push liquibase-sops-aws-rds image

on:
  push:
    tags:
      - "liquibase-sops-aws-rd/v*"

jobs:
  build_docker_image:
    uses: ./.github/workflows/reuse-workflow.yml
    with:
      container_name: liquibase-sops-aws-rd
    secrets: inherit