name: build and push alpine-awscli image

on:
  push:
    branches:
      - "main"
    paths: 
      - containers/alpine-awscli/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: containers/alpine-awscli
          file: containers/alpine-awscli/Dockerfile
          push: true
          tags: | 
            ${{ secrets.DOCKERHUB_USERNAME }}/alpine-awscli:1.0.0
            ${{ secrets.DOCKERHUB_USERNAME }}/alpine-awscli:latest
          cache-from: type=registry,ref=containers/alpine-awscli:latest
          cache-to: type=inline