name: build and push alpine-helm image


on:
  push:
    tags:
      - "alpine-helm/v*"

jobs:
  build_docker_image:
    uses: ./.github/workflows/reuse-workflow.yml
    with:
      container_name: alpine-helm
    secrets: inherit
