name: build and push alpine-helm image

on:
  push:
    branches:
      - "main"
    paths: 
      - containers/alpine-helm/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: containers/alpine-helm
          file: containers/alpine-helm/Dockerfile
          push: true
          tags: | 
            ${{ secrets.DOCKERHUB_USERNAME }}/alpine-helm:0.1
            ${{ secrets.DOCKERHUB_USERNAME }}/alpine-helm:latest
          cache-from: type=registry,ref=containers/alpine-helm:latest
          cache-to: type=inline
