name: build and push liquibase-sops-aws-rds image

on:
  push:
    branches:
      - "main"
    paths: 
      - containers/liquibase-sops-aws-rds/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: containers/liquibase-sops-aws-rds
          file: containers/liquibase-sops-aws-rds/Dockerfile
          push: true
          tags: | 
            ${{ secrets.DOCKERHUB_USERNAME }}/liquibase-sops-aws-rds:4.23
            ${{ secrets.DOCKERHUB_USERNAME }}/liquibase-sops-aws-rds:latest
          cache-from: type=registry,ref=containers/liquibase-sops-aws-rds:latest
          cache-to: type=inline