name: build and push maintenance-page image

on:
  push:
    tags:
      - "maintenance-page/v*"

jobs:
  build_docker_image:
    uses: ./.github/workflows/reuse-workflow.yml
    with:
      container_name: maintenance-page
    secrets: inherit