name: build_docker_image

on:
  workflow_call:
    inputs:
      container_name:
        description: 'Name of the container (and folder) to build and push'
        required: true
        type: string

jobs:
  reusable_docker_build_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Calculate tag
        id: calculate_tag
        run: |
          id=$(echo ${{ github.ref_name }} | awk -F'/' '{print $NF}')
          echo "tag=$id" >> $GITHUB_OUTPUT
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: containers/${{ inputs.container_name }}
          file: containers/${{ inputs.container_name }}/Dockerfile
          push: true
          tags: | 
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.container_name }}:${{ steps.calculate_tag.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.container_name }}:latest
          cache-from: type=registry,ref=containers/${{ inputs.container_name }}:latest
          cache-to: type=inline